[package]
name = "okx-exchange-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "test-okx-standalone"
path = "test_okx_standalone.rs"

[dependencies]
rust_decimal = "1.36"
rust_decimal_macros = "1.36"
chrono = { version = "0.4", features = ["serde"] }
hmac = "0.12"
sha2 = "0.10"
base64 = "0.21.7"