name: Secrets Scan

on:
  push:
    branches:
      - develop
      - stable
      - ci/*
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git -v

